# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Scott Loarie
url:              http://scottloarie.com
paginate:         1
baseurl:          /
author:
  name:           Scott Loarie
  url:            http://scottloarie.com
  email:          loarie@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/loarie/loarie.github.io
