# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Scott Loarie
url:              http://scottloarie.com
paginate:         1
paginate_path:    /blog/page:num
baseurl:          /
blogurl:          /blog/

author:           
  name:           Scott Loarie
  url:            http://scottloarie.com
  email:          loarie@gmail.com
  github:         loarie
  twitter:        loarie
  linkedin:       scott-loarie

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/loarie/loarie.github.io
